- hosts: all
  tasks:
    - name: add hosts to inventory group
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{hostvars[ansible_facts][inventory_hostname].pull_groups}}"
      changed_when: False

    - name:
      debug:
        msg: "{{hostvars[inventory_hostname]}}"

- import_playbook: playbook.yml
