- hosts: all
  tasks:
    - name: add hosts to inventory dev groups
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ inventory_hostname }}"
      changed_when: False

    - name: add hosts to inventory prd groups
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{hostvars[inventory_hostname].prd}}"
      changed_when: False

    - name: debug inventory hostname
      debug:
        msg: "{{ inventory_hostname }}"

- import_playbook: playbook.yml
