- hosts: all
  tasks:
    - name: add hosts to inventory groups
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ inventory_hostname}}[0:1]"
      changed_when: False

#    - name: add hosts to inventory prd groups
#      add_host:
#        name: "{{ inventory_hostname }}"
#        groups: "{{hostvars[inventory_hostname].prd}}"
#      changed_when: False

    - name: debug inventory hostname
      debug:
        msg: "{{ inventory_hostname }} , {{ inventory_hostname}}[0:1]"

- import_playbook: playbook.yml
