- hosts: all
  tasks:
    - name: add hosts to inventory group
      add_host:
        name: "{{ inventory_hostname }}"
        group: "{{hostvars[inventory_hostname].pull_groups}}"
      changed_when: False

    - name: add hosts to inventory group
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{hostvars[inventory_hostname].dev_groups}}"
      changed_when: False

    - name: debug inventory hostname
      debug:
        msgs: "{{hostvars[inventory_hostname.dev_groups]}}"


    - name: debug inventory hostname
      debug:
        msg: "{{ inventory_hostname }}"

- import_playbook: playbook.yml
