- hosts: all
  tasks:
###########   ADD HOST & LOAD VARIABLES #############
    - name: add hosts to inventory groups
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ inventory_hostname[0:2]}}"
      changed_when: false

    - name: load host vars
      include_vars:
        file: "./hosts/{{ inventory_hostname }}.yml"
        name: hostvar

    - name: debug inventory hostname
      debug:
        msg: "{{ inventory_hostname }} {{ inventory_hostname[0:2] }} "

    - name: debug host parameters
      debug:
        msg: "{{hostvar.prometheus}}, {{hostvar.service}}"

    - name : run role for apisix
      include_role:
        name: apisix

      when: hostlist|selectattr("name", "equalto", "ansible")|list|length != 0

###########   Run Rolebooks for host   #############
#  - name: run etcd role
#    hosts: all
#    become: yes
#    roles:
#      - role: etcd
#        ansible_pull_url: https://git.example.com/ansible.git
#    when: "etcd" in {{service}}


     # when: "apisix" in {{service}


- hosts: localhost
  tasks:
    - name: test variables
      debug:
        msg: "{{ inventory_hostname }} {{ inventory_hostname[0:2] }}  "

    - name: debug inventory hostname
      debug:
        msg: "{{ inventory_hostname }} {{ inventory_hostname[0:2] }}  "


#    - name: add hosts to inventory prd groups
#      add_host:
#        name: "{{ inventory_hostname }}"
#        groups: "{{hostvars[inventory_hostname].prd}}"
#      changed_when: False
#    - name: debug hostvars
#      debug:
#        msg: "hostvars[inventory_hostname]"




