- hosts: all
  tasks:
    - name: add hosts to inventory group
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ host_vars[inventory_hostname].pull_groups }}"
      changed_when: False
      debug:
        msg: "{{ check_hostname }}"

- import_playbook: playbook.yml
