- hosts: all
  tasks:
    - name: add hosts to inventory groups
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ inventory_hostname[0:2]}}"
        vars_files:
          - "./hosts/{{ inventory_hostname }}.yml"
      changed_when: False

#    - name: add hosts to inventory prd groups
#      add_host:
#        name: "{{ inventory_hostname }}"
#        groups: "{{hostvars[inventory_hostname].prd}}"
#      changed_when: False

    - name: debug inventory hostname
      debug:
        msg: "{{ inventory_hostname }} {{ inventory_hostname[0:2] }}  "

#    - name: debug hostvars
#      debug:
#        msg: "hostvars[inventory_hostname]"

- hosts: drapigw
  tasks:
    - name: debug host parameters
    - debug:
        msg: "{{prometheus}}"



- hosts: localhost
  tasks:
    - name: test variables
      debug:
        msg: "{{ inventory_hostname }} {{ inventory_hostname[0:2] }}  "
    - name: debug inventory hostname
      debug:
        msg: "{{ inventory_hostname }} {{ inventory_hostname[0:2] }}  "

    - name: debug hostvars
      debug:
        msg: "{{hostvars[inventory_hostname]}}"

- import_playbook: playbook.yml



