- hosts: all
  tasks:
    - name: add hosts to inventory group
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "foo.example.com.yml"
      changed_when: False

    - name:
      debug:
        msg: "{{ inventory_hostname }}"

- import_playbook: playbook.yml
