- hosts: ansible-test
  tasks:
    - debug:
        msg: "I'm host wonjin''"

- name: configure ansible-pull
  hosts: all
  become: yes
  roles:
    - role: ansible-pull
      ansible_pull_url: https://git.example.com/ansible.git
