---
- hosts: all
  tasks:
    - name: pull apisix source from git
      ansible.builtin.git:
        repo: "https://github.com/apache/apisix.git"
        dest: /usr/local

    - name: "init apisix configuration"
      template:
        src:  {{item}}
        dest: /usr/local/apisix/config.yaml
        mode: '0644'
      when: {{service}} == "apisix"

    - name: "reload apisix"
      ansible.builtin.command: "service reload apisix"
      when: {{service}} == "apisix"

    - name: "reload apisix"
      ansible.builtin.command: "service reload apisix"
      when: {{service}} == "apisix"

    - name: testing service status
      cmd: "service status apisix"



- name: install units for apisix
  template:
    dest: /etc/systemd/system
    src: "{{ item }}"
  loop:
    - apisix.service


