---
- name: load host vars
  include_vars:
    file: "./hosts/{{ inventory_hostname }}.yml"
    name: hostvar

- name: pull apisix source from git
  ansible.builtin.git:
    repo: "https://github.com/apache/apisix.git"
    dest: /usr/local/apisix/

- name: "init apisix configuration"
  template:
    src: config.yaml.j2
    dest: /usr/local/apisix/conf/config.yaml
    mode: '0644'

#- name: "restart apisix"
#  ansible.builtin.command: "service restart apisix"
#
#- name: "reload apisix"
#  ansible.builtin.command: "service reload apisix"

#- name: install units for apisix
#  template:
#    dest: /etc/systemd/system
#    src: "{{ item }}"
#  loop:
#    - apisix.service


